== Changelog PSCertificateEnrollment PowerShell Module

=== 1.0.11 (Nov 27, 2023)

* `Get-NDESCertificate` bugfix for MaxPolling argument description.
* `Get-NDESCertificate` added -UseBasicParsing to Invoke-WebRequest calls, to avoid parsing erros when running as local system account.
* `Get-NDESOTP` added -UseBasicParsing to Invoke-WebRequest calls.
* `Get-NDESCACertificate` added -UseBasicParsing to Invoke-WebRequest calls.

=== 1.0.10 (Nov 2, 2023)

* `Get-NDESCertificate` now supports waiting for certificate requests needing administrator approval for issuing.
* `Get-NDESCertificate` now cleans up the create Private Key, if the NDES server returns an error, to avoid dangling private keys.
* `Get-NDESOTP` seems to use NTLM for authentication, at least in a default setup of the NDES server, so user notification states this.
* `Get-NDESCACertificate` new. Supports downloading CA certificates from the NDES server, written to file, importing into Trusted Auth Root container, or both.

=== 1.0.9 (May 30, 2023)

* `Get-IssuedCertificate` supports the UniformResourceIdentifier SAN type now.
* `Get-IssuedCertificate` supports the id-pkix-ocsp-nocheck Extension now with the OcspNoRevocationCheck parameter. 

=== 1.0.8 (Dec 19, 2022)

* `Get-IssuedCertificate` supports requesting certificates using the machine's identity now.

=== 1.0.7 (Dec 13, 2022)

==== Added
* `Get-IssuedCertificate` supports request attributes now.
* Add StatusCodeInt property to `Get-IssuedCertificate` containing the HResult returned from the certificate authority as integer.
* Add alias "Config" für ConfigurationString Argument to `Get-IssuedCertificate`.
* `New-CertificateRequest` now supports the newly introduced Security Identifier certificate extension.
* `Get-NDESCertificate` now supports ECC keys.
* `Get-NDESCertificate` now supports HTTP basic authentication.

=== 1.0.6 (Feb 14, 2022)

==== Fixed

* Fixed an error in the NuGet Package for PowerShell Gallery.

=== 1.0.5 (Feb 14, 2022)

==== General

* Ported documentation from Markdown to ASCIIDoc.
* Include changelog with project.

==== Added

* TODO: Add support for PowerShell versions higher than 5.1.
* `Invoke-AutoEnrollmentTask` allows to trigger the scheduled tasks for certificate autoenrollment (both user and machine task).
* `New-CertificateRequest` 
** now uses 3072 bit key length by default.
** correctly specifies the KeySpec for use with legacy Cryptographic Service Providers (CSP).
* `Get-NDESCertificate` now uses 3072 bit key length by default.
* `New-SignedCertificateRequest` allows specifying the hash algorithm to use for the CMS message.
* `Install-IssuedCertificate`
** added a "-Machine" alias for the "-MachineContext" parameter.
** now features a "-Force" parameter.

==== Fixed

* Ensure correct execution if PowerShell Core is installed (loading the module on pwsh is getting prevented).
* Fixed some typos in synopsis of some commands.
* `New-CertificateRequest` allows for empty subject distringusied names.
* `Get-NDESCertificate` allows for empty subject distringusied names.

=== 1.0.4 (May 06, 2021)

==== General

* All included script files are now digitally signed. Using the module with restrictive PowerShell execution policy (e.g. AllSigned) is possible (if the signer certificate is trusted).

==== Added

* `Get-RemoteDesktopCertificate` can be used to identify the active remote desktop certificate on a system.
* `Set-RemoteDesktopCertificate` can be used to specify the active remote desktop certificate on a system.
* `New-CertificateRequest` dows not contain the lifetime signing extended key usage.

==== Bugfixes

* `Get-IssuedCertificate` refactored for proper error handling of the WSTEP protocol.

=== 1.0.3 (Apr 21, 2021)

==== General

* Fixed an issue with the digital signature of the package that was published to PowerShell gallery.
* Unified all file's encodings (UTF-8 with byte order mark).

==== Bugfixes

* `Get-CertificateHash` sometimes (when the calculated hash contained zeroes) returned an incorrect result, therefore `Get-NDESCertificate` could not be used in sime environments, because the root certification authoritie's MD5 hash was wrong.

=== 1.0.2 (APr 09, 2021)

==== General

* Removed compatibility requirements from module definition and reduced minimum PowerShell version to 4.0 to make it compatible with Windows 8.1 and Windows 2012 without further updates.

==== Added

* New Commands
** `Get-KeyStorageProvider` lists Cryptographic Service Providers (CSP) and Key Storage Provider (KSP) installed on the system.
** `Get-IssuedCertificate` can be used to submit certificate requests to online certification authorities, and to retrieve pending certificate requests by specifying the Request ID.
** `Install-IssuedCertificate` can be used to install a previously requested certificate after it has been issued by and retrieved from the certification authority.
** `Undo-CertificateArchival` can be used to un-archive a certificate that has the archive bit set.
** `New-SignedCertificateRequest` signs a PKCS#10 certificate request with a given (usually enrollment agent) certificate, and returns a PKCS#7 message.
* Improvements for `New-CertificateRequest`
** The command can now also generate keys using elliptic curves (ECDH/ECDSA)
** Add the "Document Encryption" enhanced key usage
** Verification if a given Key Storage Provider exists is now handled by `Get-KeyStorageProvider`
* Improvements for `Get-NDESCertificate`
** Verification if a given Key Storage Provider exists is now handled by `Get-KeyStorageProvider`

=== 1.0.1 (Mar 21, 2021)

==== Bugfixes

* Improvements for `New-CertificateRequest`
** Enabled to specify 512 bit in KeyLength parameter.
** Enabled to specify the pre-selected 2048 bit in KeyLength parameter..
** Signing certificates do not raise an error any more.
** Enhanced the verification routine if the specified Key Storage Provider actually exists.
* Improvements for `Get-NDESCertificate`
** Enabled to specify 512 bit in KeyLength parameter.
** Enabled to specify the pre-selected 2048 bit in KeyLength parameter..
** Signing certificates do not raise an error any more.
** Enhanced the verification routine if the specified Key Storage Provider actually exists.
** Added the alias "Exportable" for the "PrivateKeyExportable" argument.
** Moved calculation of the MD5 hash for the root certification authority certificate from .NET method X509Certificate2.GetCertHash to own function `Get-CertificateHash` to ensure compatbility with .NET versions below 4.7.
